/**
 * Binance symbol → CoinGecko asset ID mapping.
 * Covers the most common traded assets on Binance.
 */
export const BINANCE_ASSET_MAP: Record<string, string> = {
  BTC: 'bitcoin',
  ETH: 'ethereum',
  BNB: 'binancecoin',
  USDT: 'tether',
  USDC: 'usd-coin',
  BUSD: 'binance-usd',
  SOL: 'solana',
  ADA: 'cardano',
  XRP: 'ripple',
  DOT: 'polkadot',
  DOGE: 'dogecoin',
  AVAX: 'avalanche-2',
  SHIB: 'shiba-inu',
  MATIC: 'matic-network',
  POL: 'matic-network',
  LTC: 'litecoin',
  UNI: 'uniswap',
  LINK: 'chainlink',
  ATOM: 'cosmos',
  XLM: 'stellar',
  ETC: 'ethereum-classic',
  FIL: 'filecoin',
  NEAR: 'near',
  ALGO: 'algorand',
  ICP: 'internet-computer',
  VET: 'vechain',
  HBAR: 'hedera-hashgraph',
  EGLD: 'elrond-erd-2',
  XTZ: 'tezos',
  AAVE: 'aave',
  GRT: 'the-graph',
  MKR: 'maker',
  COMP: 'compound-governance-token',
  SNX: 'havven',
  CRV: 'curve-dao-token',
  '1INCH': '1inch',
  SAND: 'the-sandbox',
  MANA: 'decentraland',
  AXS: 'axie-infinity',
  CHZ: 'chiliz',
  ENJ: 'enjincoin',
  BAT: 'basic-attention-token',
  ZEC: 'zcash',
  DASH: 'dash',
  XMR: 'monero',
  BCH: 'bitcoin-cash',
  BSV: 'bitcoin-cash-sv',
  TRX: 'tron',
  EOS: 'eos',
  NEO: 'neo',
  IOTA: 'iota',
  THETA: 'theta-token',
  FTM: 'fantom',
  ONE: 'harmony',
  HOT: 'holotoken',
  ZIL: 'zilliqa',
  CAKE: 'pancakeswap-token',
  OP: 'optimism',
  ARB: 'arbitrum',
  APT: 'aptos',
  SUI: 'sui',
  INJ: 'injective-protocol',
  SEI: 'sei-network',
  TIA: 'celestia',
  JUP: 'jupiter-exchange-solana',
  PEPE: 'pepe',
  WIF: 'dogwifcoin',
  BONK: 'bonk',
  FLOKI: 'floki',
  // Stablecoins
  DAI: 'dai',
  TUSD: 'true-usd',
  FDUSD: 'first-digital-usd',
  EUR: 'euro',
  GBP: 'gbp',
};

/**
 * Returns the CoinGecko asset ID for a given Binance symbol,
 * or undefined if not found.
 */
export function binanceSymbolToAssetId(symbol: string): string | undefined {
  return BINANCE_ASSET_MAP[symbol.toUpperCase()];
}
